"""Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

http://projecteuler.net/problem=2
"""


def fib(max_value):
    a = 1
    b = 2

    while True:
        if a > max_value:
            return

        yield a
        (a, b) = (b, a + b)


def sum_even_fibs(max_value):
    return sum(n for n in fib(max_value) if n % 2 == 0)
    


if __name__ == '__main__':
    reason = 'Sum of even fib values under 20 should be 2 + 8 = 10'
    assert sum_even_fibs(20) == 10, reason

    print sum_even_fibs(int(4e6))
